### PR TITLE
Add capability for StubExecute.exe to display a splash image

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This can be useful for C#/.Net programs which are notoriously slow to
start up in order to reassure users that something is happening.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/squirrel.windows/29)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Functionality looks good, but it's pretty hard to understand. Not sure how much of that is just that I'm rusty on C++ and unfamiliar with the Windows native support for bitmaps and events. I've made various suggestions. I realize some of this wasn't originally yours and my guess may be as good as yours. So take what suggestions are helpful and leave the rest. I do think minimally we need a block of comments somewhere saying what has to be done in the way of providing a bitmap and signalling the event to make it all work.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKa6XqyU9NQkQ41tCG:-KnKa6XqyU9NQkQ41tCH:b4uf17p) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L8)):*
> ```cpp
> // http://faithlife.codes/blog/2008/09/logos_code_blog_license/.  The revisions
> // and additions are Copyright 2017 SIL International and licensed under the same
> // MIT style license.
> ```

This feels like a good place to summarize how it works: things like how the image is named, what the exe should do to close it,...

---

*[src/StubExecutable/SplashImageUtils.cpp, line 21 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnK_ZwhHRmrQNtSHnll:-KnK_Zwi9US8sRRxtksU:b40rl83) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L21)):*
> ```cpp
> ATOM RegisterWindowClass(HINSTANCE hInstance);
> 
> // create Splash window
> ```

Maybe say a little more: that it will fail and return NULL if some other process is already waiting for the close event; what the handle is and what should be done with it; that the path is expected to be the path to the exe that the stub program is launching (or is it to the stub itself?). Also make it clearer this is one of the two main public entry points for this code.
Actually this method does three things, which is confusing and makes it hard to name. I think it would be clearer if the main program did CoInitializeEx, and this method was broken into GetWaitEventHandle() and DisplaySplashWindow(). (I guess the second of those has to be called first, since we don't need a wait handle if we don't succeed in opening a window. But then, we can also fail if something else already has made the wait event. So the logic is hopelessly intertwined. But it deserves as descriptive a name as possible...LaunchSplashWindowAndGetHandleToWaitEvent()?

---

*[src/StubExecutable/SplashImageUtils.cpp, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnK_P7IpH3kYUOhXv0n:-KnK_P7IpH3kYUOhXv0o:bt5r11q) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L33)):*
> ```cpp
> 		if (GetLastError() == ERROR_ALREADY_EXISTS)
> 			return NULL;
> 		::CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
> ```

Is it a problem if something else in the app also calls CoInitialize{Ex}? I'd favor moving Co{Un}initialize into the main program, with just a note in the header for this file that it needs them.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 70 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKfwY81DgKaEJBOWoY:-KnKfwY81DgKaEJBOWoZ:b-k83yp1) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L70)):*
> ```cpp
> }
> 
> // Creates a 32-bit DIB from the specified WIC bitmap.
> ```

I don't know what a WIC bitmap is...guessing DIB is device-independent bitmap? Is there more than one format for a bmp file? Do we need to document which are supported?

---

*[src/StubExecutable/SplashImageUtils.cpp, line 255 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKcRwlIxbjUdM1vFWa:-KnKcRwlIxbjUdM1vFWb:b-7wro9e) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L255)):*
> ```cpp
> }
> 
> inline DWORD PumpMsgWaitForMultipleObjects(DWORD nCount, LPHANDLE pHandles, DWORD dwMilliseconds)
> ```

Not sure how much it's worth trying to improve what is probably copied code, but if this was ours, I'd want either comments or better variable names to explain what nCount is counting (milliseconds between pumping messages???), handles to what, milliseconds until what?

---

*[src/StubExecutable/SplashImageUtils.cpp, line 257 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKc9PrgxVkL-T83Uy5:-KnKc9PrgxVkL-T83Uy6:b1eashq) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L257)):*
> ```cpp
> inline DWORD PumpMsgWaitForMultipleObjects(DWORD nCount, LPHANDLE pHandles, DWORD dwMilliseconds)
> {
> 	// useful variables
> ```

I suppose this is just copied code...but useful variables? Why say that? Are some useless ones going to be declared somewhere for some reason?

---

*[src/StubExecutable/SplashImageUtils.cpp, line 268 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKe9zZcQ9HQ70sPWSO:-KnKe9zZcQ9HQ70sPWSP:b-yw1gvt) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L268)):*
> ```cpp
> 			dwElapsed < dwMilliseconds ? dwMilliseconds - dwElapsed : 0;
> 
> 		// wait for a handle to be signaled or a message
> ```

This is quite obscure and I think more comment is needed. Apparently somehow it's waiting for whatever the C# program has to do...which should be documented somewhere, probably the header for this file...to signal the bootstrapper to quit? Presumably somehow signaling the event results in a WM_QUIT appearing in the event queue for hCloseSplashEvent?
Be nice if some overview said something like (this is probably not right)
 - InitSplash creates an event and returns its handle
 - bootstrapper's main program passes that handle as the second argument to PumpMessageWaitingForEvent
 - that passes it as the second handle to MsgWaitForMultipleObjects
 - ...which pumps messages (?so bitmap gets drawn? So event can be received?)...
 - until dwTimeout time elapses or main program sends event to ??
 - which translates it into a WM_QUIT on the event handle's queue
 - which causes this method to return
 - at which point the bootstrapper quits

---

*[src/StubExecutable/SplashImageUtils.cpp, line 300 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKdhXp90OZ2MXbHz5u:-KnKdhXp90OZ2MXbHz5v:b-eb4tnv) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L300)):*
> ```cpp
> {
> 	HANDLE aHandles[2] = { hProcess, hCloseSplashEvent };
> 	DWORD ret = PumpMsgWaitForMultipleObjects(2, &aHandles[0], 60 * 1000);
> ```

Is the address of aHandles[0] something different from just plain aHandles?

---

*[src/StubExecutable/SplashImageUtils.cpp, line 301 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKct-YBqpMvfH8WCjj:-KnKct-ZfgSzb8LU3fW8:b-s8e6v7) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L301)):*
> ```cpp
> 	HANDLE aHandles[2] = { hProcess, hCloseSplashEvent };
> 	DWORD ret = PumpMsgWaitForMultipleObjects(2, &aHandles[0], 60 * 1000);
> 	::CoUninitialize();
> ```

Shouldn't be in this function...maybe in the caller? Name indicates responsibility to pump messages and wait, not to shut down COM!

---

*[src/StubExecutable/stdafx.h, line 24 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKdDT5omL0g_Jng9L7:-KnKdDT5omL0g_Jng9L8:b-ipxyit) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/stdafx.h#L24)):*
> ```objc
> 
> 
> // TODO: reference additional headers your program requires here
> ```

This TODO has been done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-:-KnKjqwtCNZRNtyCSt5l:b-uu7cee)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 8 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKa6XqyU9NQkQ41tCG:-KnL7cCF6j7XWV1Vmuq3:b-896fix) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L8)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This feels like a good place to summarize how it works: things like how the image is named, what the exe should do to close it,...
</blockquote></details>

Done.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 21 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnK_ZwhHRmrQNtSHnll:-KnLPmm9a-bDPUepGBcz:b-5jeqhp) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L21)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe say a little more: that it will fail and return NULL if some other process is already waiting for the close event; what the handle is and what should be done with it; that the path is expected to be the path to the exe that the stub program is launching (or is it to the stub itself?). Also make it clearer this is one of the two main public entry points for this code.
Actually this method does three things, which is confusing and makes it hard to name. I think it would be clearer if the main program did CoInitializeEx, and this method was broken into GetWaitEventHandle() and DisplaySplashWindow(). (I guess the second of those has to be called first, since we don't need a wait handle if we don't succeed in opening a window. But then, we can also fail if something else already has made the wait event. So the logic is hopelessly intertwined. But it deserves as descriptive a name as possible...LaunchSplashWindowAndGetHandleToWaitEvent()?
</blockquote></details>

I added a longer comment to the head of the method, and also invented a longer, clunkier name that more or less describes the functionality.  Not quite the same as what you suggested, however.  :-)

---

*[src/StubExecutable/SplashImageUtils.cpp, line 33 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnK_P7IpH3kYUOhXv0n:-KnLPkp1djGkrmmcqp2G:b-896fix) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L33)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it a problem if something else in the app also calls CoInitialize{Ex}? I'd favor moving Co{Un}initialize into the main program, with just a note in the header for this file that it needs them.
</blockquote></details>

Done.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 70 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKfwY81DgKaEJBOWoY:-KnLRU2fJMtu5jFfcvCV:b7aqxc0) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L70)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't know what a WIC bitmap is...guessing DIB is device-independent bitmap? Is there more than one format for a bmp file? Do we need to document which are supported?
</blockquote></details>

The 32-bit format allows the alpha channel through, which deals with transparency if memory serves me correctly.  I don't think we need to worry about other formats.
Windows Imaging Component (aha! COM!)
Device Independent Bitmap (good guess)

---

*[src/StubExecutable/SplashImageUtils.cpp, line 255 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKcRwlIxbjUdM1vFWa:-KnLUcRBTqVq6vS7Do6i:b-15t5dg) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L255)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not sure how much it's worth trying to improve what is probably copied code, but if this was ours, I'd want either comments or better variable names to explain what nCount is counting (milliseconds between pumping messages???), handles to what, milliseconds until what?
</blockquote></details>

renamed to numHandles since it's the number of handles in the array pointed to by pHandles.  Intellisense showed nCount as the variable name for the internal win32 call, so that's probably where the name came from.  but nCount is rather undescriptive.
And I've already improved the code by removing a number of gotos.  :-)

I also merge this with the following method.  I decided it didn't clarify anything to have a pseudo-general purpose method that is poorly documented.  So I added comments specific to how we're using this code.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 257 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKc9PrgxVkL-T83Uy5:-KnLgHyzzV_wk7Qvtovm:b1e9c7k) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L257)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose this is just copied code...but useful variables? Why say that? Are some useless ones going to be declared somewhere for some reason?
</blockquote></details>

It is copied code.  I replaced the comment with some more meaningful if possibly blindingly obvious.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 300 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKdhXp90OZ2MXbHz5u:-KnLWaF9mBtSPN5c1P9i:b6afrs5) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L300)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is the address of aHandles[0] something different from just plain aHandles?
</blockquote></details>

not really.  i'll change it to just plain aHandles

---

*[src/StubExecutable/SplashImageUtils.cpp, line 301 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKct-YBqpMvfH8WCjj:-KnLW_QHfZdOVA-qGwBl:b-896fix) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L301)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Shouldn't be in this function...maybe in the caller? Name indicates responsibility to pump messages and wait, not to shut down COM!
</blockquote></details>

Done.

---

*[src/StubExecutable/stdafx.h, line 24 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKdDT5omL0g_Jng9L7:-KnL_qX4Fe5T9zsoD_Oi:b-93o6n5) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/stdafx.h#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This TODO has been done.
</blockquote></details>

Done.  I also moved the two win32 headers up to the windows header files section

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29)*

**Comment by JohnThomson** [comment]
:lgtm: Much improved; thanks for your patience. Two very minor comments, probably not worth acting on.

---

Review status: 2 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 14 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZZP9Uzjs2JCt-6zQ5:-KnZZP9Uzjs2JCt-6zQ6:b6te3ye) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L14)):*
> StubExecutetries
(If you're doing another pass :-)

---

*[src/StubExecutable/SplashImageUtils.cpp, line 53 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZZsKCe-w3e6QUSu2w:-KnZZsKCe-w3e6QUSu2x:b-yt4wnm) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L53)):*
> ```cpp
> // hInstance is the HINSTANCE handle of this program (StubExecute whatever name)
> // fullPath is the path to the real executable program.
> HANDLE ShowSplashIfNeededAndCreateCloseEvent(HINSTANCE hInstance, std::wstring exePath)
> ```

Much better name. Still leaves me wondering, how does the program know whether it is 'needed'? ShowSplashIfImageFoundAndCreateCloseEvent? But I'm not really sure that is better. And the comment spells it out.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 101 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZ_WH6mtE8sNTPX0GT:-KnZ_WH6mtE8sNTPX0GU:bo8tgn0) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L101)):*
> ```cpp
> // (WIC) bitmap source.  This allows the full 8 bits per color plus any "alpha" information which
> // controls the transparency/opacity.
> HBITMAP CreateHBITMAP(IWICBitmapSource * ipBitmap)
> ```

So can the image really be partly transparent? Or will the (white?) background of the window just show through?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-:-KnZaUR5VplIu1KGIQhs:bm793pl)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 268 at r1](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnKe9zZcQ9HQ70sPWSO:-Kn_HqScDATWvTOKem8x:bueuj4z) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/f9386f21ffa41e821c5234bf79913dab0337d5cc/src/StubExecutable/SplashImageUtils.cpp#L268)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is quite obscure and I think more comment is needed. Apparently somehow it's waiting for whatever the C# program has to do...which should be documented somewhere, probably the header for this file...to signal the bootstrapper to quit? Presumably somehow signaling the event results in a WM_QUIT appearing in the event queue for hCloseSplashEvent?
Be nice if some overview said something like (this is probably not right)
 - InitSplash creates an event and returns its handle
 - bootstrapper's main program passes that handle as the second argument to PumpMessageWaitingForEvent
 - that passes it as the second handle to MsgWaitForMultipleObjects
 - ...which pumps messages (?so bitmap gets drawn? So event can be received?)...
 - until dwTimeout time elapses or main program sends event to ??
 - which translates it into a WM_QUIT on the event handle's queue
 - which causes this method to return
 - at which point the bootstrapper quits
</blockquote></details>

I've tried to add appropriate comments to clarify what is happening in this method, and throughout the program.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 14 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZZP9Uzjs2JCt-6zQ5:-Kn_FjLW7wjavkXWFvKs:b-896fix) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L14)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

> StubExecutetries
(If you're doing another pass :-)
</blockquote></details>

Done.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 53 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZZsKCe-w3e6QUSu2w:-Kn_GocL5lhMsKnTGB2r:b5419i7) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Much better name. Still leaves me wondering, how does the program know whether it is 'needed'? ShowSplashIfImageFoundAndCreateCloseEvent? But I'm not really sure that is better. And the comment spells it out.
</blockquote></details>

renamed to ShowSplashAndCreateCloseEventIfImageFound.

---

*[src/StubExecutable/SplashImageUtils.cpp, line 101 at r2](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-KnZ_WH6mtE8sNTPX0GT:-Kn_ErfGb8bMbAu35Fpo:bxn92by) ([raw file](https://github.com/bloombooks/squirrel.windows/blob/ee124c57e34d5c6469021064a0e5ef956887c077/src/StubExecutable/SplashImageUtils.cpp#L101)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So can the image really be partly transparent? Or will the (white?) background of the window just show through?
</blockquote></details>

I think it can be partially transparent.  If the artist is really clever, it can have a gradient of becoming more or less transparent moving from one side to the other or from the outside in.  But achieving that kind of affect is beyond my graphic arts skill level.  :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/squirrel.windows/29#-:-Kn_W1oAHfgAOKf6tn7m:bnfp4nl)*

**Pull request merged**
